#!/bin/bash

# System Information
HOSTNAME=$(hostname)
OS=$(source /etc/os-release && echo $PRETTY_NAME)
UPTIME=$(uptime -p)

# Hardware Information
CPU=$(lshw -class processor | grep -m 1 "product" | cut -d ":" -f 2 | sed 's/^[ \t]*//')
CPU_SPEED=$(lscpu | grep "CPU MHz" | awk '{print $3}')
MAX_CPU_SPEED=$(lscpu | grep "CPU max MHz" | awk '{print $4}')
RAM=$(free -h | grep Mem | awk '{print $2}')
DISKS=$(lsblk -o NAME,MODEL,SIZE | grep -v "NAME")
VIDEO=$(lspci | grep VGA | awk -F': ' '{print $3}')

# Network Information
FQDN=$(hostname --fqdn)
HOST_IP=$(hostname -I | awk '{print $1}')
GATEWAY=$(ip r | grep default | awk '{print $3}')
DNS=$(systemd-resolve --status | grep "DNS Servers" | awk '{print $3}')

# Interface Information (assuming eth0 as an example)
INTERFACE=$(lshw -class network | grep "logical name:" | awk '{print $3}')
INTERFACE_MODEL=$(lshw -class network | grep -A 2 "logical name: $INTERFACE" | grep "product" | awk '{print $2}')
INTERFACE_IP=$(ip addr show $INTERFACE | grep "inet " | awk '{print $2}')

# System Status
USERS=$(who | awk '{print $1}' | sort -u | tr '\n' ',')
DISK_SPACE=$(df -h | awk '{print $1,$4}' | sed '1d')
PROCESS_COUNT=$(ps -e | wc -l)
LOAD_AVG=$(cat /proc/loadavg | awk '{print $1",",$2",",$3}')
MEMORY=$(free -h | grep "Mem:" | awk '{print "Total:",$2,"Used:",$3,"Free:",$4}')
LISTENING_PORTS=$(ss -tuln | awk 'NR > 1 {print $5}' | cut -d ':' -f 2 | sort -u | tr '\n' ',')
UFW_RULES=$(sudo ufw status numbered | sed -n '/[0-9]/p')

# Output the report
cat << EOF

System Report generated by $USER, $(date +%Y-%m-%d\ %H:%M:%S)

System Information
------------------
Hostname: $HOSTNAME
OS: $OS
Uptime: $UPTIME

Hardware Information
--------------------
CPU: $CPU
Speed: Current: $CPU_SPEED MHz, Max: $MAX_CPU_SPEED MHz
RAM: $RAM
Disks:
$DISKS
Video: $VIDEO

Network Information
-------------------
FQDN: $FQDN
Host Address: $HOST_IP
Gateway IP: $GATEWAY
DNS Server: $DNS

Interface: $INTERFACE
Model: $INTERFACE_MODEL
IP Address: $INTERFACE_IP

System Status
-------------
Users Logged In: ${USERS%?}  # Remove trailing comma
Disk Space:
$DISK_SPACE
Process Count: $PROCESS_COUNT
Load Averages: $LOAD_AVG
Memory Allocation:
$MEMORY
Listening Network Ports: ${LISTENING_PORTS%?}  # Remove trailing comma
UFW Rules:
$UFW_RULES

EOF
